### ISSUE TITLE
ShapeletForestClassifier does not support single dimension 3D input (i.e. shape (10, 1, 20))

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [isaksamsten/wildboar#74]
**Describe the bug**

ShapeletForestClassifier crashes with a single dimension 3D numpy array input as sklearn cannot process it.

```
Traceback (most recent call last):
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\local_code.py", line 18, in <module>
    rf.fit(x, y)
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\wildboar\ensemble\_ensemble.py", line 186, in fit
    self._fit(
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\wildboar\ensemble\_ensemble.py", line 240, in _fit
    return super()._fit(X, y, max_samples, max_depth, sample_weight, False)
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\sklearn\ensemble\_bagging.py", line 434, in _fit
    all_results = Parallel(
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\joblib\parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\joblib\_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\joblib\parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\joblib\parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\sklearn\utils\fixes.py", line 117, in __call__
    return self.function(*args, **kwargs)
  File "D:\CMP Machine Learning\tsmlPy-estimator-evaluation\venv\lib\site-packages\sklearn\ensemble\_bagging.py", line 84, in _parallel_build_estimators
    n_samples, n_features = X.shape
ValueError: too many values to unpack (expected 2)

Process finished with exit code 1
```

**To Reproduce**

```
import warnings
import numpy as np
from wildboar.datasets import load_dataset
from wildboar.ensemble import ShapeletForestClassifier

if __name__ == "__main__":
    warnings.simplefilter(action='ignore', category=FutureWarning)

    x, y = load_dataset("Beef")
    print(x.shape)
    rf = ShapeletForestClassifier()
    rf.fit(x, y)
    print(rf.score(x, y))

    x = np.reshape(x, (60, 1, 470))
    print(x.shape)
    rf = ShapeletForestClassifier()
    rf.fit(x, y)
    print(rf.score(x, y))
```

More than 1 dimension is fine, i.e. if you were to reshape it to (60, 2, 235).

**Expected behavior**

The classifier processes single dimension 3D input.

**Setup (please complete the following information):**
 - OS: Windows
 - Python version: 3.9
 - NumPy version: 1.22.4
 - Wildboar version: 1.1.1

**Additional context**

If this is a deliberate design decision, feel free to close.

**Comment by isaksamsten** [comment]
Thanks for the bug report.

It’s an edge case I don’t test for, but the bug is simple to fix.

I will push a fix as soon as possible.

**Comment by isaksamsten** [comment]
The issue has been resolved in master and 1.1.X, and the fix will be released as part of 1.1.2.

In the meantime you can use the following workaround `rf.fit(np.squeeze(x), y)`.

(Also, you can silence the deprecation warning by setting `n_shapelets=10`)
